<h3>Listar Funcionário</h3> 

<table class="table table-striped"> 
    <tr> <th>NOME</th> 
        <th>EDITAR</th> 
        <th>EXCLUIR</th> 
    </tr> 
    <?php foreach ($this->lista as $f): ?> 
    <tr> 
        <td><?php echo $f->getName(); ?></td> 
        <td>Editar</td> 
        <td>Excluir</td> 
    </tr> <?php endforeach; ?> 
</table> 
<a href="<?php echo $this->url('home'); ?>" class="btn btn-primary">Voltar</a>
